/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "kvcache.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ds3_kvcache_Empty, ds3_kvcache_Empty, AUTO)


PB_BIND(ds3_kvcache_ConfigResp, ds3_kvcache_ConfigResp, AUTO)


PB_BIND(ds3_kvcache_CreateSessionReq, ds3_kvcache_CreateSessionReq, AUTO)


PB_BIND(ds3_kvcache_CloseSessionReq, ds3_kvcache_CloseSessionReq, AUTO)


PB_BIND(ds3_kvcache_ResetSessionReq, ds3_kvcache_ResetSessionReq, AUTO)


PB_BIND(ds3_kvcache_StatusResp, ds3_kvcache_StatusResp, AUTO)


PB_BIND(ds3_kvcache_LookupReq, ds3_kvcache_LookupReq, AUTO)


PB_BIND(ds3_kvcache_BlockHandle, ds3_kvcache_BlockHandle, AUTO)


PB_BIND(ds3_kvcache_LookupResp, ds3_kvcache_LookupResp, AUTO)


PB_BIND(ds3_kvcache_AllocateReq, ds3_kvcache_AllocateReq, AUTO)


PB_BIND(ds3_kvcache_AllocateResp, ds3_kvcache_AllocateResp, AUTO)


PB_BIND(ds3_kvcache_StoreReq, ds3_kvcache_StoreReq, AUTO)


PB_BIND(ds3_kvcache_HeartbeatReq, ds3_kvcache_HeartbeatReq, AUTO)


PB_BIND(ds3_kvcache_StatsResp, ds3_kvcache_StatsResp, AUTO)


PB_BIND(ds3_kvcache_RpcRequest, ds3_kvcache_RpcRequest, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

