/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DS3_KVCACHE_PROTO_KVCACHE_PB_H_INCLUDED
#define PB_DS3_KVCACHE_PROTO_KVCACHE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ds3_kvcache_Empty {
    char dummy_field;
} ds3_kvcache_Empty;

typedef struct _ds3_kvcache_ConfigResp {
    bool ok;
    pb_callback_t error;
    pb_callback_t mmap_path;
    uint64_t mmap_size;
    uint32_t block_size;
    uint32_t n_layer;
    uint32_t n_kv_head;
    uint32_t head_dim;
    uint64_t per_token_kv_bytes;
} ds3_kvcache_ConfigResp;

typedef struct _ds3_kvcache_CreateSessionReq {
    pb_callback_t session_id;
} ds3_kvcache_CreateSessionReq;

typedef struct _ds3_kvcache_CloseSessionReq {
    pb_callback_t session_id;
} ds3_kvcache_CloseSessionReq;

typedef struct _ds3_kvcache_ResetSessionReq {
    pb_callback_t session_id;
} ds3_kvcache_ResetSessionReq;

typedef struct _ds3_kvcache_StatusResp {
    bool ok;
    pb_callback_t error;
} ds3_kvcache_StatusResp;

typedef struct _ds3_kvcache_LookupReq {
    pb_callback_t session_id;
    pb_callback_t tokens;
} ds3_kvcache_LookupReq;

typedef struct _ds3_kvcache_BlockHandle {
    uint64_t block_id;
    uint64_t mmap_offset;
} ds3_kvcache_BlockHandle;

typedef struct _ds3_kvcache_LookupResp {
    bool ok;
    pb_callback_t error;
    int32_t cached_prefix_len;
    pb_callback_t blocks;
    uint64_t prefix_token_hash;
} ds3_kvcache_LookupResp;

typedef struct _ds3_kvcache_AllocateReq {
    pb_callback_t session_id;
    int32_t num_blocks;
    pb_callback_t token_hashes;
} ds3_kvcache_AllocateReq;

typedef struct _ds3_kvcache_AllocateResp {
    bool ok;
    pb_callback_t error;
    pb_callback_t blocks;
} ds3_kvcache_AllocateResp;

typedef struct _ds3_kvcache_StoreReq {
    pb_callback_t session_id;
    pb_callback_t tokens;
    int32_t n_prompt;
    pb_callback_t block_ids;
    int32_t cached_prefix_len;
} ds3_kvcache_StoreReq;

typedef struct _ds3_kvcache_HeartbeatReq {
    pb_callback_t daemon_id;
    pb_callback_t session_ids;
} ds3_kvcache_HeartbeatReq;

typedef struct _ds3_kvcache_StatsResp {
    bool ok;
    pb_callback_t error;
    uint64_t total_blocks;
    uint64_t free_blocks;
    uint64_t valid_blocks;
    uint64_t reserved_blocks;
    uint64_t sessions;
    double hit_rate;
} ds3_kvcache_StatsResp;

/* Simple RPC envelope used by the custom UDS transport. */
typedef struct _ds3_kvcache_RpcRequest {
    pb_callback_t method;
    pb_callback_t payload;
} ds3_kvcache_RpcRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ds3_kvcache_Empty_init_default           {0}
#define ds3_kvcache_ConfigResp_init_default      {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define ds3_kvcache_CreateSessionReq_init_default {{{NULL}, NULL}}
#define ds3_kvcache_CloseSessionReq_init_default {{{NULL}, NULL}}
#define ds3_kvcache_ResetSessionReq_init_default {{{NULL}, NULL}}
#define ds3_kvcache_StatusResp_init_default      {0, {{NULL}, NULL}}
#define ds3_kvcache_LookupReq_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_BlockHandle_init_default     {0, 0}
#define ds3_kvcache_LookupResp_init_default      {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define ds3_kvcache_AllocateReq_init_default     {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ds3_kvcache_AllocateResp_init_default    {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_StoreReq_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define ds3_kvcache_HeartbeatReq_init_default    {{{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_StatsResp_init_default       {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define ds3_kvcache_RpcRequest_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_Empty_init_zero              {0}
#define ds3_kvcache_ConfigResp_init_zero         {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define ds3_kvcache_CreateSessionReq_init_zero   {{{NULL}, NULL}}
#define ds3_kvcache_CloseSessionReq_init_zero    {{{NULL}, NULL}}
#define ds3_kvcache_ResetSessionReq_init_zero    {{{NULL}, NULL}}
#define ds3_kvcache_StatusResp_init_zero         {0, {{NULL}, NULL}}
#define ds3_kvcache_LookupReq_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_BlockHandle_init_zero        {0, 0}
#define ds3_kvcache_LookupResp_init_zero         {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define ds3_kvcache_AllocateReq_init_zero        {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ds3_kvcache_AllocateResp_init_zero       {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_StoreReq_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define ds3_kvcache_HeartbeatReq_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}}
#define ds3_kvcache_StatsResp_init_zero          {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define ds3_kvcache_RpcRequest_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ds3_kvcache_ConfigResp_ok_tag            1
#define ds3_kvcache_ConfigResp_error_tag         2
#define ds3_kvcache_ConfigResp_mmap_path_tag     3
#define ds3_kvcache_ConfigResp_mmap_size_tag     4
#define ds3_kvcache_ConfigResp_block_size_tag    5
#define ds3_kvcache_ConfigResp_n_layer_tag       6
#define ds3_kvcache_ConfigResp_n_kv_head_tag     7
#define ds3_kvcache_ConfigResp_head_dim_tag      8
#define ds3_kvcache_ConfigResp_per_token_kv_bytes_tag 9
#define ds3_kvcache_CreateSessionReq_session_id_tag 1
#define ds3_kvcache_CloseSessionReq_session_id_tag 1
#define ds3_kvcache_ResetSessionReq_session_id_tag 1
#define ds3_kvcache_StatusResp_ok_tag            1
#define ds3_kvcache_StatusResp_error_tag         2
#define ds3_kvcache_LookupReq_session_id_tag     1
#define ds3_kvcache_LookupReq_tokens_tag         2
#define ds3_kvcache_BlockHandle_block_id_tag     1
#define ds3_kvcache_BlockHandle_mmap_offset_tag  2
#define ds3_kvcache_LookupResp_ok_tag            1
#define ds3_kvcache_LookupResp_error_tag         2
#define ds3_kvcache_LookupResp_cached_prefix_len_tag 3
#define ds3_kvcache_LookupResp_blocks_tag        4
#define ds3_kvcache_LookupResp_prefix_token_hash_tag 5
#define ds3_kvcache_AllocateReq_session_id_tag   1
#define ds3_kvcache_AllocateReq_num_blocks_tag   2
#define ds3_kvcache_AllocateReq_token_hashes_tag 3
#define ds3_kvcache_AllocateResp_ok_tag          1
#define ds3_kvcache_AllocateResp_error_tag       2
#define ds3_kvcache_AllocateResp_blocks_tag      3
#define ds3_kvcache_StoreReq_session_id_tag      1
#define ds3_kvcache_StoreReq_tokens_tag          2
#define ds3_kvcache_StoreReq_n_prompt_tag        3
#define ds3_kvcache_StoreReq_block_ids_tag       4
#define ds3_kvcache_StoreReq_cached_prefix_len_tag 5
#define ds3_kvcache_HeartbeatReq_daemon_id_tag   1
#define ds3_kvcache_HeartbeatReq_session_ids_tag 2
#define ds3_kvcache_StatsResp_ok_tag             1
#define ds3_kvcache_StatsResp_error_tag          2
#define ds3_kvcache_StatsResp_total_blocks_tag   3
#define ds3_kvcache_StatsResp_free_blocks_tag    4
#define ds3_kvcache_StatsResp_valid_blocks_tag   5
#define ds3_kvcache_StatsResp_reserved_blocks_tag 6
#define ds3_kvcache_StatsResp_sessions_tag       7
#define ds3_kvcache_StatsResp_hit_rate_tag       8
#define ds3_kvcache_RpcRequest_method_tag        1
#define ds3_kvcache_RpcRequest_payload_tag       2

/* Struct field encoding specification for nanopb */
#define ds3_kvcache_Empty_FIELDLIST(X, a) \

#define ds3_kvcache_Empty_CALLBACK NULL
#define ds3_kvcache_Empty_DEFAULT NULL

#define ds3_kvcache_ConfigResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, SINGULAR, STRING,   mmap_path,         3) \
X(a, STATIC,   SINGULAR, UINT64,   mmap_size,         4) \
X(a, STATIC,   SINGULAR, UINT32,   block_size,        5) \
X(a, STATIC,   SINGULAR, UINT32,   n_layer,           6) \
X(a, STATIC,   SINGULAR, UINT32,   n_kv_head,         7) \
X(a, STATIC,   SINGULAR, UINT32,   head_dim,          8) \
X(a, STATIC,   SINGULAR, UINT64,   per_token_kv_bytes,   9)
#define ds3_kvcache_ConfigResp_CALLBACK pb_default_field_callback
#define ds3_kvcache_ConfigResp_DEFAULT NULL

#define ds3_kvcache_CreateSessionReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1)
#define ds3_kvcache_CreateSessionReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_CreateSessionReq_DEFAULT NULL

#define ds3_kvcache_CloseSessionReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1)
#define ds3_kvcache_CloseSessionReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_CloseSessionReq_DEFAULT NULL

#define ds3_kvcache_ResetSessionReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1)
#define ds3_kvcache_ResetSessionReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_ResetSessionReq_DEFAULT NULL

#define ds3_kvcache_StatusResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define ds3_kvcache_StatusResp_CALLBACK pb_default_field_callback
#define ds3_kvcache_StatusResp_DEFAULT NULL

#define ds3_kvcache_LookupReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1) \
X(a, CALLBACK, REPEATED, INT32,    tokens,            2)
#define ds3_kvcache_LookupReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_LookupReq_DEFAULT NULL

#define ds3_kvcache_BlockHandle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   block_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   mmap_offset,       2)
#define ds3_kvcache_BlockHandle_CALLBACK NULL
#define ds3_kvcache_BlockHandle_DEFAULT NULL

#define ds3_kvcache_LookupResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, INT32,    cached_prefix_len,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            4) \
X(a, STATIC,   SINGULAR, UINT64,   prefix_token_hash,   5)
#define ds3_kvcache_LookupResp_CALLBACK pb_default_field_callback
#define ds3_kvcache_LookupResp_DEFAULT NULL
#define ds3_kvcache_LookupResp_blocks_MSGTYPE ds3_kvcache_BlockHandle

#define ds3_kvcache_AllocateReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1) \
X(a, STATIC,   SINGULAR, INT32,    num_blocks,        2) \
X(a, CALLBACK, REPEATED, UINT64,   token_hashes,      3)
#define ds3_kvcache_AllocateReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_AllocateReq_DEFAULT NULL

#define ds3_kvcache_AllocateResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            3)
#define ds3_kvcache_AllocateResp_CALLBACK pb_default_field_callback
#define ds3_kvcache_AllocateResp_DEFAULT NULL
#define ds3_kvcache_AllocateResp_blocks_MSGTYPE ds3_kvcache_BlockHandle

#define ds3_kvcache_StoreReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1) \
X(a, CALLBACK, REPEATED, INT32,    tokens,            2) \
X(a, STATIC,   SINGULAR, INT32,    n_prompt,          3) \
X(a, CALLBACK, REPEATED, UINT64,   block_ids,         4) \
X(a, STATIC,   SINGULAR, INT32,    cached_prefix_len,   5)
#define ds3_kvcache_StoreReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_StoreReq_DEFAULT NULL

#define ds3_kvcache_HeartbeatReq_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   daemon_id,         1) \
X(a, CALLBACK, REPEATED, STRING,   session_ids,       2)
#define ds3_kvcache_HeartbeatReq_CALLBACK pb_default_field_callback
#define ds3_kvcache_HeartbeatReq_DEFAULT NULL

#define ds3_kvcache_StatsResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, UINT64,   total_blocks,      3) \
X(a, STATIC,   SINGULAR, UINT64,   free_blocks,       4) \
X(a, STATIC,   SINGULAR, UINT64,   valid_blocks,      5) \
X(a, STATIC,   SINGULAR, UINT64,   reserved_blocks,   6) \
X(a, STATIC,   SINGULAR, UINT64,   sessions,          7) \
X(a, STATIC,   SINGULAR, DOUBLE,   hit_rate,          8)
#define ds3_kvcache_StatsResp_CALLBACK pb_default_field_callback
#define ds3_kvcache_StatsResp_DEFAULT NULL

#define ds3_kvcache_RpcRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   method,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           2)
#define ds3_kvcache_RpcRequest_CALLBACK pb_default_field_callback
#define ds3_kvcache_RpcRequest_DEFAULT NULL

extern const pb_msgdesc_t ds3_kvcache_Empty_msg;
extern const pb_msgdesc_t ds3_kvcache_ConfigResp_msg;
extern const pb_msgdesc_t ds3_kvcache_CreateSessionReq_msg;
extern const pb_msgdesc_t ds3_kvcache_CloseSessionReq_msg;
extern const pb_msgdesc_t ds3_kvcache_ResetSessionReq_msg;
extern const pb_msgdesc_t ds3_kvcache_StatusResp_msg;
extern const pb_msgdesc_t ds3_kvcache_LookupReq_msg;
extern const pb_msgdesc_t ds3_kvcache_BlockHandle_msg;
extern const pb_msgdesc_t ds3_kvcache_LookupResp_msg;
extern const pb_msgdesc_t ds3_kvcache_AllocateReq_msg;
extern const pb_msgdesc_t ds3_kvcache_AllocateResp_msg;
extern const pb_msgdesc_t ds3_kvcache_StoreReq_msg;
extern const pb_msgdesc_t ds3_kvcache_HeartbeatReq_msg;
extern const pb_msgdesc_t ds3_kvcache_StatsResp_msg;
extern const pb_msgdesc_t ds3_kvcache_RpcRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ds3_kvcache_Empty_fields &ds3_kvcache_Empty_msg
#define ds3_kvcache_ConfigResp_fields &ds3_kvcache_ConfigResp_msg
#define ds3_kvcache_CreateSessionReq_fields &ds3_kvcache_CreateSessionReq_msg
#define ds3_kvcache_CloseSessionReq_fields &ds3_kvcache_CloseSessionReq_msg
#define ds3_kvcache_ResetSessionReq_fields &ds3_kvcache_ResetSessionReq_msg
#define ds3_kvcache_StatusResp_fields &ds3_kvcache_StatusResp_msg
#define ds3_kvcache_LookupReq_fields &ds3_kvcache_LookupReq_msg
#define ds3_kvcache_BlockHandle_fields &ds3_kvcache_BlockHandle_msg
#define ds3_kvcache_LookupResp_fields &ds3_kvcache_LookupResp_msg
#define ds3_kvcache_AllocateReq_fields &ds3_kvcache_AllocateReq_msg
#define ds3_kvcache_AllocateResp_fields &ds3_kvcache_AllocateResp_msg
#define ds3_kvcache_StoreReq_fields &ds3_kvcache_StoreReq_msg
#define ds3_kvcache_HeartbeatReq_fields &ds3_kvcache_HeartbeatReq_msg
#define ds3_kvcache_StatsResp_fields &ds3_kvcache_StatsResp_msg
#define ds3_kvcache_RpcRequest_fields &ds3_kvcache_RpcRequest_msg

/* Maximum encoded size of messages (where known) */
/* ds3_kvcache_ConfigResp_size depends on runtime parameters */
/* ds3_kvcache_CreateSessionReq_size depends on runtime parameters */
/* ds3_kvcache_CloseSessionReq_size depends on runtime parameters */
/* ds3_kvcache_ResetSessionReq_size depends on runtime parameters */
/* ds3_kvcache_StatusResp_size depends on runtime parameters */
/* ds3_kvcache_LookupReq_size depends on runtime parameters */
/* ds3_kvcache_LookupResp_size depends on runtime parameters */
/* ds3_kvcache_AllocateReq_size depends on runtime parameters */
/* ds3_kvcache_AllocateResp_size depends on runtime parameters */
/* ds3_kvcache_StoreReq_size depends on runtime parameters */
/* ds3_kvcache_HeartbeatReq_size depends on runtime parameters */
/* ds3_kvcache_RpcRequest_size depends on runtime parameters */
#define DS3_KVCACHE_PROTO_KVCACHE_PB_H_MAX_SIZE  ds3_kvcache_StatsResp_size
#define ds3_kvcache_BlockHandle_size             22
#define ds3_kvcache_Empty_size                   0
#define ds3_kvcache_StatsResp_size               64

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
